// <auto-generated />
using System;
using AnnouncementMVC.Data.Entities;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace AnnouncementMVC.Migrations
{
    [DbContext(typeof(AnnouncementContext))]
    partial class AnnouncementContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("AnnouncementMVC.Data.Entities.Announcement", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AnnouncementDetailId")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("AnnouncementDetailId")
                        .IsUnique();

                    b.ToTable("announcements");
                });

            modelBuilder.Entity("AnnouncementMVC.Data.Entities.AnnouncementDetails", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("DateAdded")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.HasKey("Id");

                    b.ToTable("announcementsDetails");
                });

            modelBuilder.Entity("AnnouncementMVC.Data.Entities.Announcement", b =>
                {
                    b.HasOne("AnnouncementMVC.Data.Entities.AnnouncementDetails", "AnnouncementDetail")
                        .WithOne("Announcement")
                        .HasForeignKey("AnnouncementMVC.Data.Entities.Announcement", "AnnouncementDetailId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AnnouncementDetail");
                });

            modelBuilder.Entity("AnnouncementMVC.Data.Entities.AnnouncementDetails", b =>
                {
                    b.Navigation("Announcement")
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
